# Generated by Django 3.0.5 on 2020-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
