# Generated by Django 3.0.5 on 2020-11-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
    ]
